### ISSUE TITLE
Injured Reserve eligibility

### ISSUE THREAD

**Issue by dogle** [fffrontoffice/rules#43]
Are there qualifications around what constitutes eligibility for placing a player on IR?

**Comment by fffrontoffice** [comment]
Currently, this is all we have:
https://github.com/fffrontoffice/rules/blob/8f74d6ea960c7057cdbf94638cc4bb9d2efd17dd/team/roster.md

```
IR - Injured Reserve - Player must be placed on IR on their NFL team.
```
Although in the past we have allowed putting a player on IR in FF Front Office (thus eliminating their salary from your cap while they have the designation) if they are allowed in the IR spot on ESPN. I believe ESPN allows this for any player that is listed as *Out* along with the regular *IR* status.

**Comment by fffrontoffice** [comment]
I would say we should update that text to be more specific and tie it to ESPN's IR rules.

**Comment by dogle** [comment]
specific example- could a player on suspension qualify for IR? they appear as OUT in ESPN

**Comment by fffrontoffice** [comment]
ESPN doesn't allow suspended players to be put in IR slot. I'll add clarification.
