### ISSUE TITLE
Bonuses

### ISSUE THREAD

**Issue by dogle** [fffrontoffice/rules#45]
Final contingency of Kickers kicking the same distance states:
Whichever kicker has the most attractive significant other as voted upon by the significant others of all league members.

Grammatically, this means we would each need to poll our significant others, which raises a few challenges:
1. logistics of polling all of them
2. poll integrity (a significant other could be influenced or coerced)
3. What if a league member has no significant other. They would be excluded from voting and may suffer emotional distress.

**Comment by fffrontoffice** [comment]
Closing as wontfix due to temporal nature of "proximity to end of game" tie breaker making significant other poll statistically improbable. Means of poll can be decided by vote if situation does occur.
