### ISSUE TITLE
[Proposal] Move to rename Westside Warriors to the Westside Daddy Sharks

### ISSUE THREAD

**Issue by dogle** [fffrontoffice/rules#48]
Jordan really loves the Baby Shark song, and also his team has performed a bit more like a Nurse Shark than any sort of Warrior. Thus Daddy Sharks is an appropriate, nay, imperative mascot change.

Also Tom proposed this so using Github is totally worthwhile.

**Comment by fffrontoffice** [comment]
Closing as a defect inherent in human free will. Will open issue with the Universe.
