### ISSUE TITLE
Market Value Salary Increased and Rookies

### ISSUE THREAD

**Issue by dogle** [fffrontoffice/rules#59]
Players picked up while rookies (vie rookie draft or on waivers) be exempt from market value increases during the tenure of their rookie contract (and subsequent franchise options)

this better reflects the real market conditions of running an NFL franchise, increases the prospective value of draft picks, and does not punish a team for taking a risk and sitting on a rookie.

**Comment by fffrontoffice** [comment]
Discuss during 2020 season

**Comment by willy4short** [comment]
4 years of no salary increases?  You're telling me that Andrew can pay Bijan Robinson $80 for the next 4 years cus he sucked last year?  You're trying to replicate a real NFL Franchise when we are dealing with skill players that have a much shorter shelf life in their prime than others.  With the franchise tag, it is possible to hold onto a player for 6 years if you get them as a rookie.  

**OFFICIAL VOTE:** - Vote NO in favor of a market value exception for rookies

**Comment by fffrontoffice** [comment]
Verdict from rules discussion:
Not enough support. Closing.
