### ISSUE TITLE
Undrafted Rookie to Practice Squad eligibility

### ISSUE THREAD

**Issue by dogle** [fffrontoffice/rules#62]
If a team has eligible Practice Squad space (i.e.- empty positions), rookies that are picked up on the waiver wire before the season may be placed onto the practice squad. Practice squad spots lock once the first week of games begin.

**Comment by fffrontoffice** [comment]
Needs more clarity before voting.

**Comment by willy4short** [comment]
I've been thinking about this rule change for a few years now and used to be in favor of it.  My opinion now has changed.  I like that the 4 P.S. spots on our rosters are for the rookie draft only.  It adds some value to drafting a rookie and incentivizes holding onto your rookie picks.   Also, drafting a rookie adds an automatic $$$ amount to the player.  Technically a rookie could be picked up off of waivers and sit on someone's practice squad for 4 years at $0.  That doesn't seem very fair or equivalent to an actual NFL franchise.  In general, if you've made moves to improve your team this year (at the cost of future years), I'm not in favor of making it easier to "re-start" or "re-load" your team the following year.

**OFFICIAL VOTE:** - Vote NO in favor of adjusting our practice squad rosters to allow for undrafted rookies.

**Comment by fffrontoffice** [comment]
Verdict from rules discussion:
Not enough support at this time. Closing for now.
