### ISSUE TITLE
[Offseason Blind Bidding] Improvement suggestion

### ISSUE THREAD

**Issue by fffrontoffice** [fffrontoffice/rules#70]
IMHO offseason blind bidding is one of the best mechanics of the League. The great unknown, high degree of risk, and 3 day wait period makes for a uniquely nail-biting part of year. 

While forming the League, the original intention of offseason blind bidding was to last months before preseason started (with the rookie draft and live auction occurring shortly after the NFL draft). The idea was to have slow, rolling engagement with the League during the summer.

One unintended consequence of this mechanic and how it works with where the Live Auction sits moments before the regular season is that a majority of activity (and big name players) happen in the seconds and minutes after we are able to submit bids. While it does force owners to take strong stances on who they want to win, it opens the door for outrageous transactions that go under the radar as owners fumble in the dark to compete for the top available players.

Given recent improvements in the blind bidding system to allow bids that lost to an eventually cancelled bid to succeed, I would like to suggest a change that maintains the great aspects of blind bidding but allows for more competition:

> Each midnight, a bid that is currently losing to another pending bid will go into "pending loss" status and the owner will be notified. The owner may then cancel and resubmit a bid in an attempt to outbid the other pending bid. If the higher pending bid that caused the "pending loss" is cancelled, the owner of the "pending loss" bid (cancelled or not) has an option to re-activate that bid unless a higher bid was submitted.

The idea here is that an owner does not know the amount another owner is attempting to pay for a player, just that their bid isn't high enough. This will allow for more competition in the first 4 days of blind bidding where the current system has a lot of surprises on the first processing.

**Comment by joenandez** [comment]
Love this. #shipit

**Comment by fffrontoffice** [comment]
Similar to #65

**Comment by fffrontoffice** [comment]
League agrees to do nothing for now.

**Comment by willy4short** [comment]
Love this.

**OFFICIAL VOTE:** - Vote YES in favor of "pending losing" for blind bidding.

**Comment by fffrontoffice** [comment]
Verdict from rules discussion:
Proposal passes 9 for, 1 against.
