### ISSUE TITLE
Make blind bidding process at 10pm

### ISSUE THREAD

**Issue by fffrontoffice** [fffrontoffice/rules#78]
We're old and are too excited to see if we won, give us a break.

**Comment by joenandez** [comment]
I'd advocate for even earlier. E.g., BB processes at like 7pm, enabling evening chatter with the rest of the owners.

**Comment by willy4short** [comment]
**OFFICIAL VOTE:** - Vote YES for early bedtime!!!

**Comment by fffrontoffice** [comment]
Verdict from rules discussion:
Approved for 7pm (9 votes support, 0 against)
