### ISSUE TITLE
Reduce Blind Bidding Period to 24 hours

### ISSUE THREAD

**Issue by joenandez** [fffrontoffice/rules#79]
I love the blind bidding mechanic, but the 3 day wait makes it more difficult for owners to exert control over their lineup. The waiting period combined with the 'blind-ness' leads to situations where owners in less advantageous financial positions wait and wait only to lose bids to owners in better financial situations, then upon redeploying $ may already be too late to acquire players they could have won and likely needed.

Proposal to consider a 24 hr bidding period. This puts far more weight on the first few days of blind bidding, which is when most league owners are paying the most attention anyway. 

Just an idea - open for thoughts and what other league dynamics this may introduce and what any positive/negative effects might be.

**Comment by joenandez** [comment]
Another idea would be a rolling 24hr period, where winning bids are the highest bid for a 24hr period.

**Comment by willy4short** [comment]
**OFFICIAL VOTE:** - Vote YES for 24hr period!
