### ISSUE TITLE
Make Blind Bidding Tie-Breaks Sudden Death

### ISSUE THREAD

**Issue by joenandez** [fffrontoffice/rules#80]
The new BB tie breaking rules are great, but follow-up auctioning between the tied owners is time consuming to accomplish manually and (not trying to speak for Tom but pls chime in) would be both logistically and technically complex to deliver via software. 

Propose that we make Tie Breaking Bids sudden death. Each owner gets a chance to bid on the player in question (blind to the bids of the other owner), and highest bid automatically wins. If bids are tied, process repeats until one owner bids more than the other. 

As articulated by Dave:

Ex-
Joe and david both tie @ $0
Joe bids $1, david bids $3 in the OT bid round. David automatically wins the player no rebuttal for Joe.

Ex 2-
Joe and david both tie @ $0
Joe bids $1, david bids $1 in the OT bid round. OT extended another round
Joe bids $2 david bids $3. David automatically wins the player no rebuttal for Joe.

**Comment by willy4short** [comment]
**OFFICIAL VOTE:** - Vote YES in favor of making blind bidding tie-breaks sudden death.

**Comment by fffrontoffice** [comment]
Verdict from rules discussion:
Approved 10 for, 0 against.
