### ISSUE TITLE
Make all trades open to counter offers for a period

### ISSUE THREAD

**Issue by joenandez** [fffrontoffice/rules#81]
To further incentivize trading and increase value equivalency in trades, we could potentially consider giving all trades a 24hr 'counter-offer' window, where the terms of the trade become public and any owner can counter offer the terms with their own proposal. If no counters are accepted within 24hrs, the trade can be processed. If a counter is accepted, that counter trade can be processed immediately. (also open to adding another 24hr period, but recognizing many trades would like to be executed against to utilize players for the next week)

This could lead to better value exchanges of a 3rd owner could offer better terms to either of the owners, and the period of considering trade-terms could lead other owners who may NOT have been considering a trade to do so.

**Comment by willy4short** [comment]
This idea looks pretty innocent at first glance and I understand the thought behind it Joe for sure.  However, I'd feel pretty slighted if I had discussed, proposed, and agreed to terms on a deal with an owner and was undercut by a leaguewide feeding frenzy.  It's sort of up to both owners to do their homework beforehand right?  Maybe for some reason you don't want to trade a certain asset to a divisional foe, even though that team might be able to beat the price.  I'm open for a channel on slack allocated to an "optional" league announcement if an owner wants to post before accepting a trade.

**OFFICIAL VOTE:**  - Vote NO for the 24hr mandatory counter offer window.

**Comment by fffrontoffice** [comment]
Verdict from rules discussion:
Proposal did not pass. Closing.
