### ISSUE TITLE
[Blind Bidding] Allow Trades as mechanism to get within cap/roster limits if an owners goes OVER as a result of Blind Bidding wins

### ISSUE THREAD

**Issue by joenandez** [fffrontoffice/rules#82]
One of the downsides of Blind Bidding is that you can easily go over your roster and cap limits in an attempt to maximize your opportunity/competitiveness for players. 

Today, the rules state that a player must drop players and/or terminate existing contracts in order to free up roster/cap space to sign their new players. As we learned from this weekend, trades to get within roster/cap limits are not allowed.

### Proposal

**_I'd like to propose that we allow trades as a mechanism to get within cap/roster limits during Blind Bidding_**.
* Keep the same 24hr warning, 48hr hard cap to get within roster limits
* Owners would still not be allowed to bid on any new players
* Any players 'won' in subsequent blind bidding periods should be forfeit if the owner has not corrected roster/cap limits (further incentivizing resolving quickly)
* Owner can only trade with existing contracted players. So you cannot trade away the players you 'won' but haven't signed due to cap/roster overages.

The rationale for allowing trades, is that I think it might be overly punitive to require an owner to drop existing contracted players to free up cap if they get lucky and go over cap. This could also introduce another incentive to initiate trades, which we've all agreed would be good for the health of the league.

### Example

Using my specific example, I bid $35 for two IDPs, both of which did not get acquired early in the week (there was active bidding on them). I had $36 of cap space, and did not expect to win both. But I did. My only option would have been to drop AJ Brown (a top 10-15 WR) to get within cap limits. Instead, it would be less punitive if I was able to make a trade in this situation, including the contracts for the players I "won" in Blind Bidding.

While I'm trading players I don't own, the value equation for the owner and other potential owners involved in a trade is definitely unique. E.g., the downside of not landing a trade with equitable value exchange is that I'd have to find the cap space myself within 48 hrs, and in many cases this is not a positive outcome (e.g., cancelling AJ Brown's contract). Thus, the owner on the other side of this trade can extract more value than perhaps they otherwise would be able to since the owner with the cap/roster overage is in a disadvantageous position.

The player in question still gets paid the amount bid for their contract. The owner that bid on that player has to give up equivalent value to the other owner. The other owner gets value back as well. Win win all around.

### Risks/Mitigations

Would this lead to owners bidding up players they know they can't afford and then using them as trade-pawns? Possibly, but it would be extremely risky to do so. The player won in BB has a $ value associated to them, and if not 'traded' within 48 hrs to an owner willing to fund that $ value, the BB winning owner is required to cancelling existing contracts to make up the $$.

So while people may use this mechanic add trade-able value to their roster, it is extremely risky and the down-side risk can/will be taking advantage of in the value exchange with another owner.

### Conclusion

I anticipate the vast majority of owners would use this mechanic (allowing trades to get within roster/cap limits during blind bidding) to make better roster decisions pre-season and not as a way to abuse the system. I don't see much upside to owners taking advantage of such a mechanic. 

Open to other thoughts of course.

**Comment by fffrontoffice** [comment]
Yeah, this aligns with the spirit of how things should work when a team goes over roster limits or cap space. I think the verbiage was just over-prescriptive/short-sighted in calling out "drop" as being the only way to get within limits.

I do want to make sure there is a callout that the trade-able players are those already on the team, not the ones that sent the team over the limit. Formalize how players aren't really on the team for dropping/trading/starting until room has been made for them. 

Also, if players send the team over the limit in a batch (like when processing offseason bids), then I would say they are all treated as equals and the trades/drops must come from the contracts that existed before the batch was processed. That way we don't have to pick and choose which player(s) from the batch could be tradeable. None of them would be.

**Comment by willy4short** [comment]
**OFFICIAL VOTE:** - Vote YES in favor of allowing trades to get within cap space.

**Comment by fffrontoffice** [comment]
Verdict from rules discussion:
8 votes in favor, 3 oppose.
