### ISSUE TITLE
Trade deadline: announcement vs execution

### ISSUE THREAD

**Issue by fffrontoffice** [fffrontoffice/rules#85]
Current verbiage indicates declaration of a trade must occur before the deadline:

> Trade Deadline: After Week 8 - Last day to declare a trade is 12:00 PM PST the Wednesday before Week 9.

However since declaration alone does not equate to agreement of terms by both parties (e.g. if there is a typo, one of the terms was missed, the other party wasn't completely agreed on the trade yet), then there is risk that the trade could change after declaration and before execution.

**Proposal** - Update rule to indicate that the trade must be declared and executed by the deadline so there is no room for questioning the terms or delaying the transaction.

**Comment by willy4short** [comment]
**OFFICIAL VOTE:** - Vote YES in favor of updating that the trade must be declared AND executed by the deadline.

**Comment by fffrontoffice** [comment]
Verdict from rules discussion:
8 votes in favor (no dissenting votes), will be enacted.
