### ISSUE TITLE
Adjustment to roster spots

### ISSUE THREAD

**Issue by Utelax34** [fffrontoffice/rules#88]
I propose we change one running back spot to a flex spot. 

running backs are too sparse to require two slots. With 12 teams you need 24 starting running back to fill all those slots. Many teams use running back by committee,

If one or more of a teams starting running backs go down for the season there is little to no free agency availability for replacement running backs. You you could have their handcuff but many times their handcuff is not as good as the starter and that slot may score more points if allowed to play a wr.

**Comment by fffrontoffice** [comment]
I recall our discussions on this last year over draft weekend. Generally positive sentiment on allowing for more ways to win. Also for consideration would be to make one of the WR slots a flex as well (1 RB, 1 WR, 3 FLEX).

**Comment by jsmunro24** [comment]
Rbs are hard to come by, which also makes it fun and requires more strategy. I don't want to get rid of an rb spot. Adding a flex (maybe in place of kicker?! Or IDP) is a Great idea but having only one rb is really changing the strategy and continuity of the league.

**Comment by Utelax34** [comment]
I get your point Jordan. I still argue for the change. It isn’t strategy when your starting running backs gets injured mid season and you either have to fill it with a the handcuff (who isn’t usually as good), some backfield by committee running back you have on your bench, or the dregs of the waiver wire. That’s just bad luck and it ranks your season as you can’t replace that production since the position is locked. 
I have had this happen in both that past 2 seasons where my star running back goes down, and I went from playoff contender to consolation bracket because of it. We need more options for those who have bad luck and have a RB go down. I see more strategy in allowing more started options than banking a bunch of backups on your bench who are likely to suck as a replacement.

**Comment by ClubAtletico** [comment]
Love the 1RB, 1WR, 3Flex idea. The hardest thing to overcome in this league are injuries at the RB spot. Giving teams more ways to adjust when things go wrong will encourage owners to stay motivated later in the season.

**Comment by willy4short** [comment]
I've fought this one for a few years.  I like how difficult it is to find running backs.  Personally I'm going to officially vote against this one, however if this is the direction the league wants to go I probably won't fight it too hard. 

**OFFICIAL VOTE:** - Vote NO for the motion to switch an RB slot to a flex slot.
