### ISSUE TITLE
FOR DISCUSSION: Last Place and keeping interest at end of season

### ISSUE THREAD

**Issue by fffrontoffice** [fffrontoffice/rules#9]
Looking for a little discussion around incentivizing involvement late in the season for teams out of the playoff race. [The current rule](https://github.com/fffrontoffice/rules/blob/ba65a0bfd8f0be1c7fc2c09b7e8c34fe98619baa/league/dues.md#last-place-fee) to support this is a $20 penalty for the worst regular season record (or you pay $20 for 1st pick in the rookie draft if you want to look at it from the _glass half full_ perspective). 

One suggestion would be to have last place be the result of the loser of the consolation bracket. So we could have a true "last place championship" or "toilet bowl" or "sacko bowl". Those out of the playoffs would fight for their lives to stay out of the week 15-16 matchup to crown the true loser. 

There could be a slew of options around this. Draft order could still be based on regular season standings and a last place fee could still be incurred. The toilet bowl champion could incur another fee, split the fee ($10 for last place, $10 for toilet bowl champ), procure trophy or championship t-shirt or something. Open for discussion.

**Comment by tomf009** [comment]
Throwing this out there: we could limit the consolation bracket to 6 teams (instead of 8) to incentivize teams to make the top 10. Bottom two teams could play a 4 week toilet bowl for the 1st pick in the draft the next year and potentially the last place fee.

**Comment by fffrontoffice** [comment]
Closing this one out... if there is a more specific issue to be raised, we can track in a new issue.
